apiVersion: v1
metadata: 
    name: ci-httpdappservice
kind: Service
spec: 
    selector:
        app: my-httpdapp
    type: ClusterIP
    ports:
      - protocol: TCP 
        port: 80 
        targetPort: 80
        