apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: oneingress 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec: 
  ingressClassName: nginx 
  rules: 
    - host: a66bfa20ed51d4234b8c124118197183-1252452707.ap-south-1.elb.amazonaws.com
      http:
        paths: 
          - path: / 
            pathType: Prefix
            backend:
              service:
                name: ci-nginxappservice
                port:
                  number: 80
          - path: /tomcat
            pathType: Prefix
            backend:
              service:
                name: ci-tomcatappservice
                port:
                  number: 8080
          - path: /httpd
            pathType: Prefix
            backend:
              service:
                name: ci-httpdappservice
                port:
                  number: 80
              